### ISSUE TITLE
Big Issue: @Latest version from jsDeliver does not load anymore!

### ISSUE THREAD

**Issue by Thimows** [editor-js/paragraph#77]
We have a lot of client editor instances using the @latest version from jsDeliver for the paragraph block, we can't force update those. All those text editors are now broken:

<img width="724" alt="Screenshot Oct 18" src="https://github.com/editor-js/paragraph/assets/62159496/7533b410-0c53-453f-9b76-c265b172c215">

**Comment by neSpecc** [comment]
Try this URL:

```
https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest/+esm
```

**Comment by Thimows** [comment]
Thank you@neSpecc Yes that works, **however** that is not the file URL that is used in the editor instances for my clients. They use the file URL from my image that I can't change as they need to update it manually. I am afraid I will get a lot of bug reports in the coming hours. Is it possible to make the original file URL work like it did before? -> https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest

**Comment by neSpecc** [comment]
Ok, I understand. Why do you load this package manually? Because it is included at the Editor.js core and it's no need to connect it manually. Only if you're using a customized version of it

**Comment by Thimows** [comment]
Thanks @neSpecc. I had problems as it did not seem to be connected automatically for me. Including it separately fixed it. However, the latest update seems to crash the whole instance unfortunately. Would it be possible to make this: https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest work again? Thank you so much.

**Comment by neSpecc** [comment]
That's probably happen because you're passing it to the EditorConfig via `tools`, right?

**Comment by Thimows** [comment]
@neSpecc yes I think that is the case. The issue unfortunately is that the editor is distributed as a plugin to my clients for their apps. The version of those text editors is fixed meaning, I can't update the code on their behalf and all of those editors are now broken. As long as those clients not update the plugin (just pushed a fix), it will be broken in their live apps as they still use: `https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest`. If that file URL works like it did before all editors will be working again. Do you think that can be fixed on your side?

**Comment by neSpecc** [comment]
I've purged jsdelivr cache and https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest seems to be working

**Comment by Thimows** [comment]
@neSpecc Thank you so much! I will remove the connection to this tool. Thanks again!

**Comment by pateljannat** [comment]
@neSpecc 

https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest 

This is still not working for me.

**Comment by Thimows** [comment]
Sorry I also have to confirm that https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest does not seem to work in production. It also seems like @latest and https://cdn.jsdelivr.net/npm/@editorjs/paragraph@2.10.0 are 2 different files, but not sure if that has anything to do with it. I might have still something to do with the URL itself. Can't we just revert back to 2.10.0?

**Comment by pateljannat** [comment]
> Anyway, for you it's better to remove manual connection of this tool and update your app

Need to do this to `preserveBlank`

**Comment by neSpecc** [comment]
Jsdelivr always returns `application/node` mime type for `.cjs` files. And Vite creates `.cjs` UMD bundle for modern ESM packages. 

I had to remove "type": "module" from our package.json. It should work now, but it probably will be changed back soon because this project uses ES Modules.

It's better to specify the exact version of package instead of using `@latest` when you have no ability to deliver updates to your clients.
